services:
  go:
    container_name: go
    build:
      context: .
      dockerfile: containers/go/Dockerfile
    volumes: 
      - './go:/app'
    ports:
      - '8080:8080'
    command: air -d
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
volumes:
  db_data: